<a href="https://colab.research.google.com/github/qor0530/BaekjoonPS/blob/main/fontfinding_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
 import sys
 import tensorflow as tf
 import keras
 from keras.models import Sequential
 from keras.layers import Dense, Dropout, Flatten
 from keras.layers.convolutional import Conv2D, MaxPooling2D
 import numpy as np

 img_rows = 28
 img_cols = 28

 (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

 input_shape = (img_rows, img_cols, 1)
 x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
 x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

 x_train = x_train.astype('float32') / 255.
 x_test = x_test.astype('float32') / 255.

 print('x_train shape:', x_train.shape)
 print(x_train.shape[0], 'train samples')
 print(x_test.shape[0], 'test samples')

 batch_size = 128
 num_classes = 10
 epochs = 12  #여러번 학습하면 좋겠지만 시간관계상 3번만 학습하고 결과를 확인합니다.

 y_train = keras.utils.to_categorical(y_train, num_classes)
 y_test = keras.utils.to_categorical(y_test, num_classes)

 model = Sequential()
 model.add(Conv2D(32, kernel_size=(5, 5), strides=(1, 1), padding='same', activation='relu', input_shape=input_shape))
 model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
 model.add(Conv2D(64, (2, 2), activation='relu', padding='same'))
 model.add(MaxPooling2D(pool_size=(2, 2)))
 model.add(Dropout(0.25))
 model.add(Flatten())
 model.add(Dense(1000, activation='relu'))
 model.add(Dropout(0.5))
 model.add(Dense(num_classes, activation='softmax'))
 model.summary()

 model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
 hist = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(x_test, y_test))

 score = model.evaluate(x_test, y_test, verbose=0)
 print('Test loss:', score[0])
 print('Test accuracy:', score[1])

ValueError: ignored

In [65]:
import pandas as pd

df = pd.read_parquet('/content/drive/MyDrive/hangul-font-dataset-main/gothic/GOYANGDEOGYANG B.pq')
df.Image[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [59]:
import pandas as pd
import numpy as np
from PIL import Image

df = pd.read_parquet('/content/drive/MyDrive/hangul-font-dataset-main/gothic/GOYANGDEOGYANG B.pq')

data =Image.fromarray(df.Image[0])
data.save('gfg_dummy_pic.png')
print()

<class 'numpy.ndarray'>
(4096,)
(64, 64)
[[  0   1   2 ...  61  62  63]
 [ 64  65  66 ... 125 126 127]
 [128 129 130 ... 189 190 191]
 ...
 [ 64  65  66 ... 125 126 127]
 [128 129 130 ... 189 190 191]
 [192 193 194 ... 253 254 255]]
<class 'numpy.ndarray'>
[0 0 0 ... 0 0 0]


IndexError: ignored